### ISSUE TITLE
Tslint show JsFailure message "Set is not defined".

### ISSUE THREAD

**Issue by rchatsiri** [joost-de-vries/play-angular2-typescript#26]
I run web application with command line  ```sbt run```.  After open application with port 9000 is ```http://localhost:9000/```  an  present an error message as below. What's a points problems on Tllint configuration file name ```tslint.json```?

```
com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure:
E:\workspacescala\play-angular2-typescript\project\target\node-modules\webjars\tslint\lib\error.js:29
var shownWarnings = new Set();
                        ^
ReferenceError: Set is not defined
    at Object.<anonymous> (E:\workspacescala\play-angular2-typescript\project\target\node-modules\webjars\tslint\lib\error.js:29:25)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (E:\workspacescala\play-angular2-typescript\project\target\node-modules\webjars\tslint\lib\configuration.js:23:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

        at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:215)
        at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:187)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
        at scala.util.Try$.apply(Try.scala:161)
        at scala.util.Success.map(Try.scala:206)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] (web-assets:tslint) com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure:
```

**Comment by joost-de-vries** [comment]
The error means that your javascript engine doesn't include an implementation of ES6 Set. You should upgrade your nodejs version to one that does.
